### ISSUE TITLE
WordPress implementation is flawed

### ISSUE THREAD

**Issue by JakeAustwick** [ezkl/sniffles#2]
The current WordPress implementation is flawed, it simply checks for "wp-content" anywhere within the source. This will pick up things such as hotlinking to images within the wp-content folder on your domain, or any other domain for that matter.

Suggestion is to use Nokogiri to parse the document, and then check if any link tags(CSS) contain "wp-content".

**Comment by ezkl** [comment]
Agreed. I haven't fleshed out the library's implementation at all, just working through TDD-style. If you feel like writing either a failing test or patching the current implementation, you're more than welcome. If not, I can take care of it at some point in the next day or two.
