### ISSUE TITLE
Depth / Detail Option

### ISSUE THREAD

**Issue by JakeAustwick** [ezkl/sniffles#3]
Not sure on the best implementation, but maybe an "depth" option could be added, which affects how much analysis is actually run. You may only want to find the platform of the site for instance, or may not be interested in that at all and only actually want to know what javascript libraries it uses.

Not sure what you think of this, or it you have ideas on the best way to implement this?

**Comment by ezkl** [comment]
I like it. We'll have to toy around with implementation.

**Comment by dchuk** [comment]
I think grouping the types of stuff it's looking for would be handy. Say for instance you want to scrape a bunch of domains and look for both 1) the analytics they're running and 2) the ad network code they're running, I wouldn't really care about their CMS or JS libs, etc. So passing in a hash of groups could be cool.

**Comment by ezkl** [comment]
What do you think of an implementation like: `Sniffles.sniff(html, :all)`, `Sniffles.sniff(html, [:google_analytics, :mixpanel, :adsense])`, or something along those lines?

**Comment by dchuk** [comment]
yeah that could work just fine, though as this thing grows, the list of platforms could be really long to put into the options. There isn't really much you can do about that though I suppose. That's why I suggested we go with groups rather than each specific one, so like for your example it would just be:

Sniffles.sniff(html, [:analytics, :advertising])

**Comment by ezkl** [comment]
Somehow glazed over that bit in your previous comment. I totally agree.

On Fri, Mar 2, 2012 at 2:52 PM, dchuk <
reply@reply.github.com

**Comment by ezkl** [comment]
I've added the ability to select sniffers individually or by group to v0.1.0, so I'm going to close this for now. Feel free to re-open it if you've got any feedback on the functionality.
