### ISSUE TITLE
Should create a wiki page for all targeted platforms to keep track of things

### ISSUE THREAD

**Issue by dchuk** [ezkl/sniffles#5]

**Comment by JakeAustwick** [comment]
Started on it here, I probably missed alot however. https://github.com/ezkl/sniffles/wiki/Platforms-to-support

**Comment by ezkl** [comment]
Thanks, guys.

**Comment by ezkl** [comment]
For the sake maintenance, I think I'd like to move the list of unsupported platforms to individual issues.

Thoughts?

**Comment by JakeAustwick** [comment]
I'm fine with this, I guess it means we can mark them off easier once they are implemented.

**Comment by ezkl** [comment]
Working on this now, so I'm closing this issue.
